# Generated by Django 5.1.2 on 2025-01-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('tags', models.TextField()),
                ('topic', models.CharField(max_length=255)),
                ('read_time', models.IntegerField()),
                ('claps', models.IntegerField()),
                ('url', models.URLField()),
                ('date_posted', models.DateField()),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
    ]
