# Generated by Django 5.1.2 on 2025-01-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_articlereaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleReaction',
        ),
    ]
