# Generated by Django 5.1.2 on 2025-02-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.CharField(max_length=5),
        ),
    ]
