# Generated by Django 5.1.2 on 2025-02-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_article_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(),
        ),
    ]
