# Generated by Django 5.1.2 on 2025-03-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_article_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreaction',
            name='reaction',
        ),
        migrations.AddField(
            model_name='userreaction',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
