# Generated by Django 5.1.2 on 2025-03-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userreaction_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
