# Generated by Django 5.1.2 on 2025-03-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userreaction_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
